server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672

  zipkin:
    baseUrl: http://localhost:9411/

  application:
    name: api-series

  data:
    mongodb:
      username: usrseriesdb
      password: pwdseriesdb
      database: seriesdb
      port: 27018
      host: localhost

  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.int}

management:
  endpoints:
    web:
      exposure:
        include: info
  info:
    env:
      enabled: true

info:
  app:
    name: api-series
    description: Series

